version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "requirements-ci.txt"
      - "requirements-min.txt"
      - "docs/requirements.txt"
