on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
      fail-fast: false

    steps:
    
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Set up Python 3.11
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
      with:
        python-version: '3.11'

    - name: Install conda dependencies
      uses: mamba-org/setup-micromamba@4b9113af4fba0e9e1124b252dd6497a419e7396d # v1
      with:
        micromamba-version: '2.0.5-0'
        environment-file: environment-test.yml
        init-shell: bash
        cache-environment: true
        post-cleanup: 'environment'

    - name: Install pip dependencies
      run: pip install .[dev]
      shell: bash -el {0}

    - name: Set up R
      uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
      with:
        r-version: '4.4.1'
        use-public-rspm: true

    - name: Configure R package repositories
      run: |
        echo "options(repos = c(mobilityteam = 'https://mobility-team.r-universe.dev', CRAN = 'https://cloud.r-project.org'))" >> ~/.Rprofile
      shell: bash

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
      with:
        cache: true

    - name: Test with pytest
      run: pytest --cov --log-cli-level INFO --clear_inputs
      shell: bash -el {0}
