on:
  push:
    branches: [ "main" ]
    path-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    path-ignore:
      - '**.md'

jobs:
  tests-pinned:
    uses: ./.github/workflows/test-reusable.yml
    with:
      requirements_file: requirements-ci.txt
      use_min_dep_versions: false
