on:
  workflow_call:
    inputs:
      requirements_file:
        required: true
        type: string
      use_min_dep_versions:
        required: false
        type: boolean
        default: false

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/mobility-team/mobility-ci:ubuntu-24.04-r-4.4.1-py3.12
    strategy:
      max-parallel: 5
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Select Python dependencies
      run: |
        if [[ "${{ inputs.use_min_dep_versions }}" == "true" ]]; then
          python_env="/opt/venv-min"
        else
          python_env="/opt/venv-ci"
        fi

        echo "VIRTUAL_ENV=${python_env}" >> "${GITHUB_ENV}"
        echo "${python_env}/bin" >> "${GITHUB_PATH}"
        echo "Using pre-installed Python dependencies from ${python_env}"
      shell: bash

    - name: Install current package
      run: |
        uv pip install --python "${VIRTUAL_ENV}/bin/python" -e . --no-deps
      shell: bash

    - name: Lint with flake8
      if: ${{ !inputs.use_min_dep_versions }}
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash

    - name: Test unit with pytest
      if: ${{ !inputs.use_min_dep_versions }}
      run: |
        python -m pytest tests/back/unit --cov=mobility --cov-config=.coveragerc --cov-append --log-cli-level=INFO --clear_inputs
      shell: bash

    - name: Test integration with pytest
      if: ${{ !inputs.use_min_dep_versions }}
      run: |
        python -m pytest tests/back/integration --cov=mobility --cov-config=.coveragerc --cov-append --log-cli-level=INFO --clear_inputs
      shell: bash

    - name: Build coverage report
      if: ${{ !inputs.use_min_dep_versions }}
      run: |
        python -m coverage xml -o coverage.xml
      shell: bash

    - name: Test with pytest without coverage
      if: ${{ inputs.use_min_dep_versions }}
      run: |
        python -m pytest --log-cli-level=INFO --clear_inputs
      shell: bash

    - name: Upload coverage reports to Codecov
      if: ${{ !inputs.use_min_dep_versions }}
      uses: codecov/codecov-action@v5
      with:
        files: coverage.xml
        verbose: true
